# Generated by Django 5.1.4 on 2024-12-19 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_user_firstname_user_lastname_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.project'),
        ),
    ]
